export const PERMISSIONS = {
  DASHBOARD_READ: 'dashboard.read',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  RESEARCH_READ: 'research.read',
  RESEARCH_CREATE: 'research.create',
  OPPORTUNITIES_READ: 'opportunities.read',
  COMPETITORS_READ: 'competitors.read',
  ANALYTICS_READ: 'analytics.read',
  PRICING_READ: 'pricing.read',
  PRICING_CALCULATE: 'pricing.calculate',
  MARKETPLACES_READ: 'marketplaces.read',
  MARKETPLACES_MANAGE: 'marketplaces.manage',
  USERS_READ: 'users.read',
  USERS_INVITE: 'users.invite',
  USERS_UPDATE: 'users.update',
  USERS_REMOVE: 'users.remove',
  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_UPDATE: 'organization.update',
  ORGANIZATION_DELETE: 'organization.delete',
  AUDIT_READ: 'audit.read',
} as const;

export type PermissionName = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_NAMES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  ANALYST: 'analyst',
  VIEWER: 'viewer',
} as const;

export type RoleName = typeof ROLE_NAMES[keyof typeof ROLE_NAMES];

export const ROLE_PERMISSIONS: Record<string, PermissionName[]> = {
  owner: Object.values(PERMISSIONS),
  admin: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_UPDATE, PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.RESEARCH_READ, PERMISSIONS.RESEARCH_CREATE,
    PERMISSIONS.OPPORTUNITIES_READ,
    PERMISSIONS.COMPETITORS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.PRICING_READ, PERMISSIONS.PRICING_CALCULATE,
    PERMISSIONS.MARKETPLACES_READ, PERMISSIONS.MARKETPLACES_MANAGE,
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_INVITE, PERMISSIONS.USERS_UPDATE, PERMISSIONS.USERS_REMOVE,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.ORGANIZATION_READ, PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.AUDIT_READ,
  ],
  analyst: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.RESEARCH_READ, PERMISSIONS.RESEARCH_CREATE,
    PERMISSIONS.OPPORTUNITIES_READ,
    PERMISSIONS.COMPETITORS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.PRICING_READ, PERMISSIONS.PRICING_CALCULATE,
    PERMISSIONS.MARKETPLACES_READ,
  ],
  viewer: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.OPPORTUNITIES_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.MARKETPLACES_READ,
  ],
};

export function roleHasPermission(role: string, permission: PermissionName): boolean {
  const perms = ROLE_PERMISSIONS[role];
  return perms ? perms.includes(permission) : false;
}
